### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by MadMarox** [IDEA-Research/DWPose#21]
Hello, i have an issue after installed DWPose. When i generate a preview it gives me back this herror: TypeError: unhashable type: 'dict'
I made a google search to fix the problem but it's very tricky for me because i'm not a programmer. There is a way to fix it ?
This is the full issue message:
 
Traceback (most recent call last):
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 635, in run_annotator
    result, is_image = preprocessor(
  File "C:\Program Files\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
TypeError: unhashable type: 'dict'

**Comment by yzd-v** [comment]
We can only help you to solve the problem with DWPose. This problem seems to be with ControlNet.
