### ISSUE TITLE
DWPose cv2.error: Unknown C++ exception from OpenCV code

### ISSUE THREAD

**Issue by freemde23** [IDEA-Research/DWPose#35]
all other models of the ControlNet v1.1.313 can be used, except DWPose,how to fix this error?

Traceback (most recent call last):
  File "o:\sd-webui-aki-v4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "o:\sd-webui-aki-v4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "o:\sd-webui-aki-v4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "o:\sd-webui-aki-v4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "o:\sd-webui-aki-v4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "o:\sd-webui-aki-v4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "o:\sd-webui-aki-v4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 675, in run_annotator
    result, is_image = preprocessor(
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
    return func(*args, **kwargs)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
    return remove_pad(self.model_openpose(
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
    poses = self.detect_poses_dw(oriImg)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 326, in detect_poses_dw
    keypoints_info = self.dw_pose_estimation(oriImg.copy())
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 29, in __call__
    det_result = inference_detector(self.session_det, oriImg)
  File "O:\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\openpose\cv_ox_det.py", line 103, in inference_detector
    output = session.forward(outNames)
cv2.error: Unknown C++ exception from OpenCV code

**Comment by yzd-v** [comment]
Try to update opencv >= 4.7. Maybe the problem would be solved.
